# Заголовок

In [ ]:
import math

In [ ]:
print(math.comb(12, 3))

In [ ]:
math.comb(12, 5)

In [ ]:
math.factorial(5)

In [ ]:
import math as m

In [ ]:
m.gcd(120, 210, 360)

In [ ]:
m.lcm(10, 20, 30, 40)

In [ ]:
import numpy as np

In [ ]:
a = np.arange(1, 13).reshape(4, 3)
print(a)
print('Transpose')
print(a.transpose())
print('Turn left')
print(np.rot90(a))
print('Turn right')
print(np.rot90(a, -1))

In [ ]:
print(a.mT)
print(a.T)

In [31]:
import numpy as np
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(a.sum(axis=0))
print(a.sum(axis=1))
print(a.min(axis=0))
print(a.max(axis=1))

[12 15 18]
[ 6 15 24]
[1 2 3]
[3 6 9]


In [36]:
a = np.arange(1,16).reshape(3,5)
print(a)
print(a[:2,3:])
print()
print(a[::2,::2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 4  5]
 [ 9 10]]

[[ 1  3  5]
 [11 13 15]]
